### ISSUE TITLE
1.7 Release: Accordion Menu Carets Don't Rotate

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/baltimorecountymd.gov-assets#105]
You can see this in dev currently -- prod is not affected until tonight's release: http://www.baltimorecountymd.gov/Agencies/animalservices/index.html.

Red carets to the right of accordion menus don't rotate when expended. Related to the top-level highlighting change in this release? Not a showstopper in the least.

**Comment by martypowell** [comment]
@danfox01 confirmed, i will try to get to this 8/28

**Comment by martypowell** [comment]
@danfox01 in progress
