### ISSUE TITLE
BaltCoGo: Hide "Enter a Location" in progress bar for requests that don't require it

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/baltimorecountymd.gov-assets#119]
**Current functionality:** Some request types are designed to skip the location step. When this occurs, the progress bar still shows "Location" as a step event though that panel is hidden, which has caused some confusion to users.

**Expected behavior:** When an issue type is selected that does not require location, the location step should disappear from he progress bar entirely. (See screen shot mockup.)

![fireshot capture 26 - request service or repo_ - https___www baltimorecountymd gov_iwant_report html](https://user-images.githubusercontent.com/13049389/30545796-ad291b8a-9c58-11e7-93f2-b7a1702f48c6.png)

**Comment by martypowell** [comment]
@danfox01 this is in progress
