### ISSUE TITLE
BaltCoGo: Convert Common Phone Formats Automatically

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/baltimorecountymd.gov-assets#121]
In the "Phone" field, Citysourced requires numbers in XXX-XXX-XXXX format. The app should accept other common phone formats and convert them into the required format upon submission.

Common formats are:
- 1234567890
- (123)4567890
- (123)456-7890
- 123.456.7890

Anything other than these formats should still trigger the phone field error message.

I believe @martypowell was working on this a while back. Not sure how far he got.

**Comment by martypowell** [comment]
@danfox01 I remember doing this, I'll have to take a look and figure out where I put that logic.

**Comment by martypowell** [comment]
#122

**Comment by martypowell** [comment]
@danfox01 this is in progress
