### ISSUE TITLE
Breadcrumb Color default browser color on non visited link

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/baltimorecountymd.gov-assets#16]
![image](https://cloud.githubusercontent.com/assets/1933400/21930356/b0a0b218-d963-11e6-9366-db331f986ce9.png)

In [red-inside.css](http://www.baltimorecountymd.gov/sebin/l/v/red-inside.css)  #baco_breadcrumb needs to have the color set to #002280;

**Comment by mxsnyder** [comment]
@sdurphy will you take care of this since red-inside.css doesn't live in Github yet?

**Comment by mxsnyder** [comment]
@sdurphy has addressed.
@martypowell will you verify this is fixed in production and close out the issue? Thanks!

**Comment by martypowell** [comment]
Sorry, did not see this, verified
