### ISSUE TITLE
Animal issue determination shouldn't work off issue name

### ISSUE THREAD

**Issue by mxsnyder** [baltimorecounty/baltimorecountymd.gov-assets#165]
https://github.com/baltimorecounty/baltimorecountymd.gov-assets/blob/82723302cae8cad7b1ad5b8632c9b244ed5bec5d/js/page-specific/baltcogo-app/BaltCoGoReporterCtrl.js#L229

**Comment by mxsnyder** [comment]
Updated title; to reflect that we don't have to use the ID or issue name, we can just add a boolean in the JSON.

**Comment by martypowell** [comment]
Resolved by #167
