### ISSUE TITLE
BaltcoGo - JSON files cached

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/baltimorecountymd.gov-assets#168]
When there is a change to the data files  (.json), changes aren't always apparent due to caching.

**Comment by danfox01** [comment]
@martypowell, I don't think BaltCoGo JSON files are cached any more are they? This might be closeable?

**Comment by martypowell** [comment]
@danfox01 this is still an issue.

**Comment by danfox01** [comment]
@tmccoy529, I think this is what we want to tackle next, per a chat I had with @martypowell.

**Comment by tmccoy529** [comment]
@danfox01 @martypowell alright sounds good to me. I'll start looking into it.

**Comment by danfox01** [comment]
Thanks! I'm not sure what options we have, but a global solution for all our JSON files would be ideal. There are JSON issues on the BCPL site as well: https://github.com/baltimorecounty/BCPL-assets/issues/626. 

Basically, wherever we're updating JSON, we have a need for the changes to show quickly without clearing cache.

**Comment by martypowell** [comment]
Steps to Verify this task is completed

1. Verify that moving that when the constants file is moved out of the main javascript file that there is no behavior changes
1. Verify that you can update categories.json for the BaltcoGo App, and "bust the cache". This will mimic a common situation web services needs this change.
  1. Make changes to constants file
  1. Upload
  1. You should see the category changes without clearing your cache.

@tmccoy529 @sgrg1

**Comment by tmccoy529** [comment]
@danfox01 this has been pushed to dev and is ready for testing

**Comment by jdomasky** [comment]
OK, I'll test today and directly report the results to @danfox01 for triage. Ideally there won't be anything to report.

**Comment by tmccoy529** [comment]
Sure, its magic!!!! 

Basically the constant.js file, which is what is used to pull in the categories.json file, wasn't always being loaded "new" through the browser because it was combined with other files that were previously cached. So the browser was looking at an old constants file with the json data inside. When you cleared your cache all those files were reloaded for the browser so the new constants code was loaded new thereby pulling in any changes to the categories file. Breaking this file out and adding it as a source inside of each template forces it to update each time the page is hit not just when you clear your cache. That's the theory anyway and so far it looks valid.

@martypowell is that accurate or was my magic comment more so?

**Comment by danfox01** [comment]
Sweet. I like it.

**Comment by danfox01** [comment]
@tmccoy529, Jason noticed that dev is using the IDs fir CitySourced prod. For testing, we should use the CitySourced stage IDs, which are in a separate JSON file... somewhere in Github. Should just be a file change but we can chat on Monday with Marty if you need a hand finding it.

**Comment by tmccoy529** [comment]
@danfox01 Oh that was probably my fault. I was testing changes and I must have moved the prod file over instead of the Dev file. I can move the dev over now.

**Comment by danfox01** [comment]
@jdomasky, try again with the staging issue types?

**Comment by jdomasky** [comment]
OK @danfox01, I've made a note to test again first thing Tuesday morning.

**Comment by danfox01** [comment]
Thanks. Reminder to everyone that tomorrow is dev refresh day. @tmccoy529 we'll need you to please redeploy to dev afterward so we can finish testing.

**Comment by jdomasky** [comment]
@danfox01 I'm ready to start testing when @tmccoy529 confirms that this has been pushed to dev again.

**Comment by jdomasky** [comment]
@danfox01 @tmccoy529 I'll be available for testing after 1:00 today. I'll let you know when I start.

**Comment by jdomasky** [comment]
@danfox01 Starting the BaltCoGo Test Plan now.

**Comment by jdomasky** [comment]
@danfox01 @tmccoy529 The BaltCoGo Reporter in dev passed the Test Plan.

**Comment by danfox01** [comment]
Sweet, thanks! @tmccoy529, @martypowell when do we want to deploy in prod?

**Comment by danfox01** [comment]
@tmccoy529 @martypowell -- let's try to get this one into prod early next week as week as well. let me know what you need from me to make that happen.

**Comment by danfox01** [comment]
@sdurphy, please work with Marty and Tim to make sure we can blow away the dynamic head in order to properly test this.

**Comment by sdurphy** [comment]
@tmccoy529, are your changes in place on the following page?: https://dev.baltimorecountymd.gov/iwant/report.html

**Comment by tmccoy529** [comment]
@sdurphy I think since dev has been updated from prod, I'll need to update the headers again. Give me like 30 mins and Ill update them again.

**Comment by sdurphy** [comment]
@tmccoy529, can you confirm that the following page is working properly now?: https://dev.baltimorecountymd.gov/iwant/report.html

**Comment by martypowell** [comment]
@sdurphy @tmccoy529 i am seeing the constants file loaded on that page, so we are in business. Do you mind sharing what you did sam?

**Comment by sdurphy** [comment]
@martypowell, @tmccoy529, here's what I did:

- Navigate to the folder containing the report page.
- Select the "Dynamic Style Sheet" tab.
- From the dropdown that appears select, "Templates Collection/Red-Inside".
- Select the remove substitution button.
- In the row for the head section select the blue View Information icon on the far right. This will display the default head section, and parent head section.
- Copy everything listed in default head section.
- Paste into the head section field.

**Comment by danfox01** [comment]
Closing the loop ...  is this good to go? I'm moving to Ready for Release -- let me know if it shouldn't be.

**Comment by tmccoy529** [comment]
@danfox01 I think this is fine to move now that the dynamic style sheet issue was resolved.

**Comment by danfox01** [comment]
@tmccoy529 @martypowell is this ready to go? Can potentially get it out the door this week, just to get it off the list?

**Comment by martypowell** [comment]
i think this may be another victim of the dev refresh. @tmccoy529 I know we have a lot going on, lets talk about how we are looking for deliverables next week to see if we can integrate this (we could also put this in as a hotfix during the day potentially.

**Comment by tmccoy529** [comment]
@danfox01 @martypowell I would suggest this be a hot fix to be honest. Its 95% site executive updates. The PR for this has already been completed. The Constants.js file just needs to be copied over to BCPL and .Gov and then those templates (ex: BCPL-Blog, Red_Inside) need to have the reference added. I don't think this needs to wait for a release for that. Unless you all want to go one more round of testing?

**Comment by martypowell** [comment]
@tmccoy529 I'm okay with this, it looks like the code hasn't been moved to master branch. Let me put in the "remove dist" pr on this repository and then we will look to move these changes to master. @danfox01 can we plan on making these changes tomorrow morning (3/28)?

**Comment by martypowell** [comment]
@sdurphy will identify which pages contain dynamic stylesheets so that we can make this change.

fyi @danfox01 @sdurphy

**Comment by sdurphy** [comment]
@martypowell it looks like the Dynamic Content tab is really not dynamic... I removed the substitutions for a folder in dev, added some CSS to the red inside template (and published) to test, and SE still would not update the section with the new CSS changes to the template. I'm testing more, but may have to reach out to systems to see if there's a way to batch reset dynamic content on folders.

**Comment by sdurphy** [comment]
@martypowell I put in a ticket with Systems... and I should clarify its Dynamic Stylesheets, not Dynamic Content.

**Comment by danfox01** [comment]
Released with 1.18.5
