### ISSUE TITLE
Swiftype: Utilize "log_clickthrough" endpoint to track search term clickthroughs on .gov

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/baltimorecountymd.gov-assets#179]
Swiftype can track clickthroughs for all search queries but we're not currently capturing that info in our BCG site search.

https://swiftype.com/documentation/analytics#recording_clickthroughs

**Comment by martypowell** [comment]
@mxsnyder what would we use as the **id** for this?

FYI, @danfox01

**Comment by mxsnyder** [comment]
Each document in the results has both an “id” and “enternal_id” value. The “id” value should be fine. However, neither value is reflected in the web service results, so you’ll need to add it.

**Comment by martypowell** [comment]
resolved with release [v1.12](https://github.com/baltimorecounty/baltimorecountymd.gov-assets/releases/tag/v1.12)
