### ISSUE TITLE
Baltcogo - Update categories json to include a isWebsite flag

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/baltimorecountymd.gov-assets#180]
Right now we are checking static text, and this caused an issue, because the text changed.

Like isAnimal, add isWebsite and make the appropriate changes.

[See here](https://github.com/baltimorecounty/baltimorecountymd.gov-assets/blob/integration/js/page-specific/baltcogo-app/BaltCoGoReporterCtrl.js#L262)

**Comment by mxsnyder** [comment]
I recommend instead of isWebsite, using a flag like isLocationHidden, or isAutomaticLocation, since the location defaults to the court house.

**Comment by martypowell** [comment]
@mxsnyder good point, I will use the existing ```requiresLocation``` flag

**Comment by martypowell** [comment]
resolved with #183
