### ISSUE TITLE
Inside pages on mobile search input close android keyboard repeatedly

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/baltimorecountymd.gov-assets#199]
@danfox01 fyi.

**Comment by danfox01** [comment]
Good catch. Looks like it's just the search input, correct? I couldn't replicate the issue on forms, etc.

@martypowell or @mxsnyder, can you please fast track a fix for this?

**Comment by martypowell** [comment]
@danfox01 I can hop on it
