### ISSUE TITLE
Table Columns Widths Change When Filtering 

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/baltimorecountymd.gov-assets#20]
**Steps to replicate:**

1. Visit [http://www.baltimorecountymd.gov/iwant/apply.html](http://www.baltimorecountymd.gov/iwant/apply.html)
2. Enter "volunteer" in the filter to observe column width change as you type

**Expected behavior:**

Column width should remain unchanged when filtering.

**Comment by martypowell** [comment]
The solution to this problem for tables is to set the table 'table-layout' to 'fixed'. Then the team must go into the specific page that includes the tables and adjust the percentage width of column headers in which they want to change. This change will come in the Content Filter Update

**Comment by danfox01** [comment]
@martypowell: @sdurphy wants to test this on a few tables in DEV before moving forward, He'll let us know if this is cool.

**Comment by sdurphy** [comment]
I want to test this after the pushdown of prod to dev (May 23) is complete. The dev version of the filter does not work.

**Comment by martypowell** [comment]
@sdurphy @danfox01 any updates on this?

**Comment by martypowell** [comment]
closing as css changes are implemented.  FYI, in the case that "Then the team must go into the specific page that includes the tables and adjust the percentage width of column headers in which they want to change." @danfox01 @sdurphy
