### ISSUE TITLE
Severe Weather Filter Input Width

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/baltimorecountymd.gov-assets#21]
http://www.baltimorecountymd.gov/News/weather/index.html

Table filter tool input doesn't span the width of the table. We might just remove the filter entirely -- I'm not sure it's necessary on this page.

**Comment by martypowell** [comment]
@danfox01 I actually think removing the filter is a pretty good idea. The list is very short, and unless it grows quite a bit its easily visible on desktop and doesn't require much scrolling on mobile. If this in fact is the approach then we would want someone on your team to update that page?

**Comment by danfox01** [comment]
@martypowell Yup, let's just remove the filter. However, I don't see and markup for it on the page. Can you use your developer magic to figure out how it's being rendered and remove it?

**Comment by martypowell** [comment]
Resolved with https://github.com/baltimorecounty/baltimorecountymd.gov-assets/commit/a8ae7abe9ce6ff16c8abdb0246298d2a82b84529
