### ISSUE TITLE
Some request types need to fire a callout box with specific instructions, and prevent the user from going further in the app.

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/baltimorecountymd.gov-assets#217]
We need to add issue types to the BaltCoGo reporter that are not in the backend system. When these issues are selected, the user should immediately see a callout with instructions and be prevented from logging an issue.

For example:
1. Assume a user wants to report a broken water line, which is not a native BaltCoGo issue type.
1. The user selects "Broken Water Line" from the drop down menu.
1. A callout immediately appears in the content area of the app that says, "Water main issues must be reported to Baltimore City by calling 123-456-7890 or visiting the[ Baltimore City Public Works website](#)."
1. The "Next" button should disappear, become unclickable, etc. The user should not be able to proceed with this issue.

Additional requirements:

- Callouts must be unique to specific issue types.
- Callouts must support HTML styling -- bullets, heading, inline links.
- Issue types that trigger the callout could be on the first or second level -- solution must support both.

Mockup:
![fireshot capture 077 - request service or rep_ - https___www baltimorecountymd gov_iwant_report html](https://user-images.githubusercontent.com/13049389/39136718-dc65751a-46e9-11e8-8631-722ac31375e1.png)

**Comment by tmccoy529** [comment]
@danfox01 I'm looking through some of these enhancements and this one appears to be a duplicate of #249 that we just worked on.

Its slightly different but with the fix for 249 all these requirements should be met for this one as well.

**Comment by danfox01** [comment]
Yeah, actually... I think there is a third issue floating around somewhere that @martypowell opened, that's also a duplicate of this. I'll close this one, since #249 will resolve this.
