### ISSUE TITLE
Change source account for BaltCoGo Twitter feed

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/baltimorecountymd.gov-assets#218]
We have a custom page set up that displays recent Twitter and FB posts from BCG accounts. The customer would like to change the Twitter account to pull from https://twitter.com/@BACOemergency instead of the current https://twitter.com/BaltCoGov.

This will require a code update in the service, per Mike:

> It’s an .gov API change (that should really be a config setting) that is quick, but then the API has to be deployed. 

I have the TFS link highlighting the line that needs to be changed. Let em know when you're ready.

**Comment by martypowell** [comment]
yep
