### ISSUE TITLE
Document BCG Services

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/baltimorecountymd.gov-assets#219]
https://services.baltimorecountymd.gov

Related to https://github.com/baltimorecounty/BCPL-assets/issues/410

**Comment by martypowell** [comment]
@danfox01 this is available on tests services (shared link via email)

**Comment by martypowell** [comment]
@danfox01 this is ready for release, we will need to continually be monitoring these for changes.

**Comment by danfox01** [comment]
@martypowell, do we need need to be concerned about the error indicator at the bottom of the page?

**Comment by martypowell** [comment]
on hold for #222

**Comment by martypowell** [comment]
confirmed, not accessible outside county network.
