### ISSUE TITLE
Site search autocomplete text too large on sub-pages

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/baltimorecountymd.gov-assets#22]
Compare autocomplete text size on homepage (http://www.baltimorecountymd.gov) to a subpage ex: (http://www.baltimorecountymd.gov/Agencies/health/animalservices/index.html).

Subpage text size should match home page.

**Comment by martypowell** [comment]
@danfox01 Fix can be found here, http://dev.baltimorecountymd.gov/Agencies/budfin/911center/index.html

**Comment by martypowell** [comment]
@danfox01 I actually think removing the filter is a pretty good idea. The list is very short, and unless it grows quite a bit its easily visible on desktop and doesn't require much scrolling on mobile. If this in fact is the approach then we would want someone on your team to update that page?

**Comment by danfox01** [comment]
Confirmed.

**Comment by martypowell** [comment]
@danfox01 Fix will go live on the next full release.
