### ISSUE TITLE
Update Animal Services spay/neuter calculator with new grant changes

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/baltimorecountymd.gov-assets#220]
https://www.baltimorecountymd.gov/Agencies/animalservices/spay-neuter.html

Spay/neuter calculator logic needs to be updated to reflect a grant change. I am still gathering the requirements and will post here when I have them.

**Comment by danfox01** [comment]
Thanks. Never heard back on requirements.

**Comment by danfox01** [comment]
The west-side ZIP codes need to be removed from the calculator:
- 21228
- 21227
- 21244
- 21207

These previously triggered a free appointment at the SWAP clinic. Now, they should be treated as all other ZIPs that are eligible for the standard $20 appointment.

All other criteria (remaining ZIPs, pet types, and free appointments for public assistance) should stay as-is.

**Comment by danfox01** [comment]
Made these changes in DEV. @martypowell please let me know if you need me to do anything else for prod.

**Comment by martypowell** [comment]
@danfox01 i will put these changes into staging first thing in the am, and share the link.

**Comment by danfox01** [comment]
@sdurphy moved to Prod. Looks good. @martypowell do you need to do anything else to finalize this or can I close?

**Comment by martypowell** [comment]
@danfox01 go ahead and close
