### ISSUE TITLE
Enable IP logging for BaltCoGo/CitySourced

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/baltimorecountymd.gov-assets#222]
The CitySourced API allows IP addresses to be captured along with service requests, but we don't have it enabled on our end so the data isn't being passed through. We've been asked to enable it. I think we're looking to enable "OriginationIPAddress," but it's sometimes a guessing game with their API.

**Comment by martypowell** [comment]
@danfox01 I will push this to test after our release meeting later today.

**Comment by danfox01** [comment]
@martypowell , ready for testing?

**Comment by martypowell** [comment]
@danfox01 let me check after a couple of prs

**Comment by danfox01** [comment]
@martypowell, where can this be tested?

**Comment by martypowell** [comment]
http://testservices.bcpl.info/swagger/ui/index

**Comment by martypowell** [comment]
https://dev.baltimorecountymd.gov/iwant/report.html?categoryID=1011065

**Comment by martypowell** [comment]
https://dev.baltimorecountymd.gov/iwant/report.html?categoryID=1011065

**Comment by danfox01** [comment]
@martypowell, IPs aren't appearing in the test console where other KVPs would show.

![fireshot capture 079 - citysourced console - simplifying ci_ - https___console citysourced net_pa](https://user-images.githubusercontent.com/13049389/40005225-6c1db1aa-5765-11e8-9725-4a3f29140fb4.png)

**Comment by martypowell** [comment]
Per our convo earlier, you can test this in dev.

https://dev.baltimorecountymd.gov/iwant/report.html?categoryID=1011065

**Comment by danfox01** [comment]
@martypowell this looks good to me. Moving to Ready, but let's talk about the release plan when you have a moment.
