### ISSUE TITLE
BaltcoGo - Add ability to disable form on certain sub categories

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/baltimorecountymd.gov-assets#235]
I talked to Eric today and he suggested we want to disable  or hide next prev buttons when a certain subcategory is selected. We should use this opportunity to finish this issue as well #169 . More details to follow.

**Comment by etenney** [comment]
Please let me know if you need anything else.

**Comment by danfox01** [comment]
Bingo. @martypowell and @tmccoy529, closing this. Duplicate of #249
