### ISSUE TITLE
Implement Google Custom Search on .Gov Site

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/baltimorecountymd.gov-assets#237]

**Comment by danfox01** [comment]
@martypowell, is it possible to somehow provide feedback to the user on what their search term was? Either by retaining the search term in the input box on the results page, or by adding a line before the results, like, "Results for **{search term}**"

I don't think this is is natively possible with the Google widget, so you'd need to get creative. It's a nice to have -- only worth the effort if it's easy, say, 2 hours or less.

**Comment by martypowell** [comment]
@danfox01 available in dev.

**Comment by danfox01** [comment]
Looks good @martypowell

**Comment by martypowell** [comment]
red-custom-index template needs reworked, all the changes have not been implemented properly and the hamburger menu does not work.

**Comment by danfox01** [comment]
@martypowell can I close this?

**Comment by danfox01** [comment]
Released in 1.16.
