### ISSUE TITLE
Smartbanner throwing errors

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/baltimorecountymd.gov-assets#238]
A console errors is thrown on this page. https://www.baltimorecountymd.gov/iwant/apply.html

We do not want this error to show.

**Requirements**
- Remove the script from our site
- Remove the banner from these pages
  - https://www.baltimorecountymd.gov/iwant/report.html
  - https://www.baltimorecountymd.gov/Agencies/publicworks/solid_waste/collectionconnection.html

**Comment by martypowell** [comment]
@danfox01 where are we using smartbanner. It looks like we are including it on every page, but based on that library we only want to include it on the pages that require it.

**Comment by danfox01** [comment]
@martypowell it should just be these two pages:

- https://www.baltimorecountymd.gov/iwant/report.html
- https://www.baltimorecountymd.gov/Agencies/publicworks/solid_waste/collectionconnection.html

**Comment by jdomasky** [comment]
I had an issue related to SmartBanner this week:
 
On January 23 around 1 p.m., I used IE 11 to browse http://staging.baltimorecountymd.gov/economicdev/jobconnectortoolkit.html
 
I clicked a PDF link on the page and it did not open in a new window, as it should. The PDF displayed in the IE 11 window using the Acrobat Pro PDF browser plugin.
 
I clicked the Back arrow and returned to the page. That is when I saw the pop-up (2nd screenshot, below).
When I clicked the Yes button in the pop-up, the IE inspector tool opened in a separate window with the Console pane displayed (1st screenshot).
 
![script error on dot_gov page in staging - pop-up 20190123](https://user-images.githubusercontent.com/13354985/51772190-63634700-20b9-11e9-9df7-2d129705d38e.png)
 
![script error on dot_gov page in staging - console 20190123](https://user-images.githubusercontent.com/13354985/51772197-69592800-20b9-11e9-83dc-da20c884f8e3.png)

**Comment by martypowell** [comment]
@jdomasky thanks, this has been bothering me for sometime, hopefully we can take a look soon.

@tmccoy529 @sgrg1

**Comment by sgrg1** [comment]
Issue fixed, waiting for it to move to dev environment

**Comment by tmccoy529** [comment]
@danfox01 This has been moved to dev for testing.

**Comment by martypowell** [comment]
@sgrg1 this can be removed from the two pages listed above @danfox01 made the decision to remove this and that sounds like a delightful idea to me.

**Comment by martypowell** [comment]
@danfox01 the script has been removed as a result of 1.18.5. The banner still exists in production. on the pages identified in this thread. Do you want me to the banner from these pages?

**Comment by danfox01** [comment]
@martypowell thanks, if you don't mind, that's be fantastic.

**Comment by martypowell** [comment]
@danfox01 these pages have been updated, and i confirmed the banners are not showing in ios or android mobile browsers as tested on browserstack.
