### ISSUE TITLE
Revised date not displaying on pages

### ISSUE THREAD

**Issue by jdomasky** [baltimorecounty/baltimorecountymd.gov-assets#246]
The Revised date that always appeared below the content on each page is not displaying.

This issue may have started between the September 19 and 26 changes from Swiftype to Google Custom Search on the .gov and BCPL websites.

A browser inspection of a page reveals the Revised date in the mainContent div, but the .reviseddate class seems to be configured to display: none.

To reproduce the issue:
1. Browse: https://www.baltimorecountymd.gov/Agencies/animalservices/foster.html
2. Scroll to bottom of page.
3. Observe that the Revised date is no longer displayed between the main content and the footer.

This issue is occurring in prod and dev, in rendering and authoring.

**Comment by jdomasky** [comment]
My colleague, Julie, reminded me of a long-standing problem with the Revised date:
"The old auto revision date always looked like it had an extra space between 'Revised' and the date. This could be our chance to fix this issue."

**Comment by martypowell** [comment]
@danfox01 resolved in #247

**Comment by martypowell** [comment]
@danfox01 in production

**Comment by danfox01** [comment]
Perfect, thank you.
