### ISSUE TITLE
Add Pet Weight to Lost and Adoptable Pets

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/baltimorecountymd.gov-assets#261]
Per Eric's email

> Animal Services asked about the status of service ticket of adding animal weight to lost and adoptable pages on Baltco website.
 
> I know we spoke about this last week. Can you send me the current SQL queries for the lost and adoptable website?  I will make the update to them to include animal weight. Then, I will send it back to you/Tim to update the web service and add it to be displayed on the web pages.

We are going to attempt to remove Eric from needing to this, and are gathering information about the request via email.

**Comment by martypowell** [comment]
@tmccoy529 @sgrg1 this is a higher priority, we are still gathering info, and I'll talk to you guys once we have all of it.

**Comment by martypowell** [comment]
Per Eric


max(decode(column_name,'Weight',attribute_value,'')) Weight, 
max(decode(column_name,'Weight Units',attribute_value,'')) WeightUnits,

**Comment by martypowell** [comment]
@tmccoy529 this is probably the top priority right now.

**Comment by danfox01** [comment]
@martypowell @tmccoy529 yes, that priority is correct. Animal Services just pinged me for a status. Sounds like they're getting anxious. Is a release next week possible?

**Comment by martypowell** [comment]
yes, working on getting it into dev.

**Comment by martypowell** [comment]
confirmed with eric this is good, also tested myself

fyi @danfox01
