### ISSUE TITLE
Padding Issue, Secondary Navigation in the Styleguide

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/baltimorecountymd.gov-assets#35]
http://www.baltimorecountymd.gov/styleguide/design/navigation.html

![image](https://cloud.githubusercontent.com/assets/1933400/26057118/270b390e-3946-11e7-9ae0-c919ea4fba01.png)

**Comment by martypowell** [comment]
@danfox01 sent a request via email to you and @sdurphy to update the file since I didn't have rights.

**Comment by sdurphy** [comment]
Fix verified. Closing.
