### ISSUE TITLE
Feeds Formatted in Eastern Standard Time don't Display correctly on Homepage

### ISSUE THREAD

**Issue by sdurphy** [baltimorecounty/baltimorecountymd.gov-assets#44]
If the publish date times for the Baltimore County Now RSS are converted to EST (Eastern Standard time), the text, "undefined" shows up in the area where the date should display on the homepage. 

The feed in development has been converted to Eastern Standard Time and the error on the homepage can be observed here: http://dev.baltimorecountymd.gov/

We would like to change the publish date time zone to EST for the production RSS so that there are no inconsistencies with the date displayed on the homepage and the date an editor actually published a post.

**Comment by sdurphy** [comment]
Closing this issue. Thanks for resolving Jeffrey.

**Comment by martypowell** [comment]
Code did not get implemented

**Comment by martypowell** [comment]
@sdurphy @snydercreative @danfox01 does anyone know what happened with this?

**Comment by martypowell** [comment]
This is integrated into the master branch, not sure why this wasn't closed.
