### ISSUE TITLE
Update Animal Services Spay/Neuter Calculator with new URLs

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/baltimorecountymd.gov-assets#53]
The domain for our spay/neuter scheduling vendor (ClinicHQ) is changing from .org to .com. All links to online scheduling must be updated to reflect this.

Scheduling links included in the [Animal Services Spay/Neuter Calculator](http://www.baltimorecountymd.gov/Agencies/health/animalservices/spayneuter.html) need to point to these new locations for each clinic:

Southwest Area Park: https://clinichq.com/online/3edba5a4-9922-4e2a-87a5-c138c8e8f4a8
Dundalk: https://clinichq.com/online/144afb8f-6c15-4f15-8e16-9417a4f85823 
Baldwin: https://clinichq.com/online/564cf872-6f61-476f-8ecd-61d574a8a06f

**Comment by danfox01** [comment]
@mxsnyder and @martypowell -- Can we please push this out as a hotfix sometime this week? The vendor gave us until the end of this week to update our site. It's unclear if the old URLs will stop working entirely at that time, but I'd rather not find out. Thanks!

**Comment by martypowell** [comment]
@mxsnyder @danfox01 i can update this real quick.
