### ISSUE TITLE
Add Rescued Pets Page

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/baltimorecountymd.gov-assets#54]
1. Update the Animal Services Web Service to include Rescued Pets (depends on accela)
1. Copy existing lost pets page, and modify to use new rescued pets service method
1. Update content (web services)
1. Add age and remove Pet Tracking Heading from the Rescued Pets template

**Comment by danfox01** [comment]
@martypowell, do you want me to document the other changes to the feeds (i.e., adding age, remove Pet Tracking H3) as a a separate issue, or include here?

**Comment by martypowell** [comment]
@danfox01 added above

**Comment by danfox01** [comment]
Thanks @martypowell . Just to clarify, the pet age/heading change should be applied to all templates, including the existing lost and adoptable pets.
