### ISSUE TITLE
Accordion Nav: Add Highlighting to Top-Level Items With No Children

### ISSUE THREAD

**Issue by danfox01** [baltimorecounty/baltimorecountymd.gov-assets#71]
The accordion navigation currently used in [Econ Dev](http://www.baltimorecountymd.gov/Agencies/economicdev/index.html) and [Animal Services](http://www.baltimorecountymd.gov/Agencies/animalservices/index.html) highlights the user's current location in gold. However, this only seems to work for links that are list items. If a link has no children, it's just included at the of the nav an <a> element, and therefore doesn't get the highlight treatment.

For example, look at the Animal Services[ Jobs page](http://www.baltimorecountymd.gov/Agencies/animalservices/jobs.html) and [homepage](http://staging.baltimorecountymd.gov/animal-services-redesign/index.html), and note that the page is not highlighted in the nav.

Is there a workaround for this? If not, please tackle this as an enhancement.

**Comment by mxsnyder** [comment]
This should be a change to `/js/accordion-menu.js` since these pages are all using the "new" accordion.

**Comment by mxsnyder** [comment]
Going live in 1.7
