### ISSUE TITLE
Remove "Pet Tracking Information" from Pet Templates

### ISSUE THREAD

**Issue by martypowell** [baltimorecounty/baltimorecountymd.gov-assets#83]
On the following pages:

* http://www.baltimorecountymd.gov/Agencies/animalservices/adoption.html
* http://www.baltimorecountymd.gov/Agencies/animalservices/adoption.html

![image](https://user-images.githubusercontent.com/1933400/28522557-7211f4ec-7046-11e7-9e7f-a79ff05e517e.png)

**Comment by martypowell** [comment]
Will be fixed when #82 is closed.

**Comment by danfox01** [comment]
@martypowell, this went live in the last BCAS update, correct?

**Comment by martypowell** [comment]
@danfox01 yes, this is done.
